export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_MY_POSTS_REQUEST = "GET_MY_POSTS_REQUEST";
export const GET_MY_POSTS_SUCCESS = "GET_MY_POSTS_SUCCESS";
export const GET_MY_POSTS_FAIL = "GET_MY_POSTS_FAIL";